config/routes.rb
Rails.application.routes.draw do
  # ユーザー用認証系: URL /users/sign_in ...
  # devise_for :users => ユーザーの ログイン、ログアウト、新規登録、パスワード変更など のルーティングやコントローラを自動的に用意する。
  # skip:オプション => 不要なルーティングを削除
  # controllers:オプション => 自分で用意したコントローラに差し替える。
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations", # サインアップやアカウント編集系
    sessions: 'public/sessions' # ログイン・ログアウト系
  }

  # ユーザー側
  # scopeメソッド: ブロック内に書かれたルーティングはpathやprefixが変更することなく、module:オプションに与えられたモジュールをコントローラの中から探し出して、ルーティングするようになる。
  scope module: :public do
    root to: "homes#top"
    get "/about", to: "homes#about"

    # as:によってprefixができる
    get "/users/:id/posts", to: "users#posts", as: "user_posts"
    get "/users/:id/groups", to: "users#groups", as: "user_groups"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]

      # idが含まれるネストの書き方
      member do
        get :relationships
      end

      resources :interviews, only: [:new, :create] do
        collection do
          get :gacha
          get :draw_gacha
          get :edit_all
          patch :update_all
        end
      end
    end

    resources :posts do
      resources :comments, only: [:create, :destroy]
      # ↓なぜresource？: resourceは「:id」を使わないURLを作る。いいね機能は、ユーザーは1つの投稿に対して1つしかいいねできない。このため、いいねの削除は、ユーザーIDと投稿IDのみで、どのいいねを削除するか特定できるため、:idを必要としない。それに対し、↑のcommentsはユーザーは1つの投稿に対し、複数コメントできるため、削除をするには、[:id]で特定する必要があるのでresourcesとなる。
      resource :likes, only: [:create, :destroy]
    end

    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :comments, only: [] do
      resources :reports, only: [:new, :create]
    end

    resources :reports, only: [:destroy] do
      # idがいらないネストの書き方
      collection do
        get :complete
      end
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 管理者用認証系 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  # namespaceメソッド: ブロック内に書かれたルーティングはすべて `/admin/〜` というパスになり、引数のモジュール（シンボル）をコントローラの中から探し出して、ルーティングするようになる。「scope module: シンボル」と比べるとpathやprefixが変更される。
  namespace :admin do
    root to: "homes#top"
    delete "/user/:id", to: "homes#destroy_user", as: "destroy_user"
    get "/style_cheatsheet", to: "homes#style_cheatsheet"

    post "/languages", to: "post_options#create_language_option", as: "create_language_option"
    delete "/language/:id", to: "post_options#destroy_language_option", as: "destroy_language_option"
    resources :post_options, only: [:index]

    resources :users, only: [:show]

    resources :interviews, only: [:new, :create] do
      collection do
        get :edit_all
        patch :update_all
      end
    end

    resources :reports, only: [:index, :update] do
      member do
        get :feedback
      end
    end
  end
end

app/controllers/admin/interviews_controller.rb
class Admin::InterviewsController < Admin::BaseController

  def new
    @interview_list = Interview.where(user_id: nil).order(created_at: :asc);
    @interview = Interview.new
  end

  def create
    @interview = Interview.new(interview_params)
    @interview.user_id = nil # nilだと管理者が作成したことになる

    if @interview.save
      respond_to do |format|
        # ↓ JSが無効の環境の場合はhtml
        format.html {
          redirect_to new_admin_interview_path,
          notice: "面接質問を作成しました"
        }
        format.js { render "shared/interview_create" }
      end
    else
      redirect_to new_admin_interview_path, alert: '面接質問の作成に失敗しました。また、空の投稿はできません。'
    end
  end

  def edit_all
    @interviews = Interview.where(user_id: nil).order(created_at: :asc)
  end

  def update_all
    success = true

    params[:interviews].each do |id, attrs|
      interview = Interview.find_by(id: id, user_id: nil)

      if attrs[:_destroy] == "1"
        interview.destroy
      else
        success &&= interview.update(content: attrs[:content])
      end
    end

    if success
      redirect_to new_admin_interview_path, notice: '質問の更新に成功しました。'
    else
      @interviews = Interview.where(user_id: nil).order(created_at: :asc)
      flash.now[:alert] = "一部の質問の更新に失敗しました。"
      render :edit_all, status: :unprocessable_entity
    end
  end

  private

  def interview_params
    params.require(:interview).permit(
      :content,
    )
  end
end

app/helpers/admin/interviews_helper.rb
module Admin::InterviewsHelper
end

app/views/admin/interviews/edit_all.html.erb
<% content_for :title, "面接質問ガチャ｜質問編集" %>
<% content_for :head do %>
<% end %>
<% content_for :foot do %>
<% end %>
<% content_for :body_class, "" %>

<section class="u-sec">
  <div class="u-inner-2">
    <h1 class="u-title">質問編集</h1>

    <%= render 'shared/interview_form_edit', url: update_all_admin_interviews_path, interviews: @interviews %>

    <div class="u-mt-50">
      <p class="u-ta-r">
        <%= link_to edit_all_admin_interviews_path, class: 'u-link' do %>
          質問作成
        <% end %>
      </p>
    </div>
  </div>
</section>

app/views/admin/interviews/new.html.erb
<% content_for :title, "面接質問ガチャ｜質問作成" %>
<% content_for :head do %>
<% end %>
<% content_for :foot do %>
<% end %>
<% content_for :body_class, "" %>

<section class="u-sec">
  <div class="u-inner-2">
    <h1 class="u-title">質問作成</h1>

    <%= render 'shared/interview_form_create', interview_list: @interview_list, url: admin_interviews_path, interview: @interview %>

    <div class="u-mt-50">
      <p class="u-ta-r">
        <%= link_to edit_all_admin_interviews_path, class: 'u-link' do %>
          質問編集
        <% end %>
      </p>
    </div>
  </div>
</section>