config/routes.rb
Rails.application.routes.draw do
  # ユーザー用認証系: URL /users/sign_in ...
  # devise_for :users => ユーザーの ログイン、ログアウト、新規登録、パスワード変更など のルーティングやコントローラを自動的に用意する。
  # skip:オプション => 不要なルーティングを削除
  # controllers:オプション => 自分で用意したコントローラに差し替える。
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations", # サインアップやアカウント編集系
    sessions: 'public/sessions' # ログイン・ログアウト系
  }

  # ユーザー側
  # scopeメソッド: ブロック内に書かれたルーティングはpathやprefixが変更することなく、module:オプションに与えられたモジュールをコントローラの中から探し出して、ルーティングするようになる。
  scope module: :public do
    root to: "homes#top"
    get "/about", to: "homes#about"

    # as:によってprefixができる
    get "/users/:id/posts", to: "users#posts", as: "user_posts"
    get "/users/:id/groups", to: "users#groups", as: "user_groups"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]

      # idが含まれるネストの書き方
      member do
        get :relationships
      end

      resources :interviews, only: [:new, :create] do
        collection do
          get :gacha
          get :draw_gacha
          get :edit_all
          patch :update_all
        end
      end
    end

    resources :posts do
      resources :comments, only: [:create, :destroy]
      # ↓なぜresource？: resourceは「:id」を使わないURLを作る。いいね機能は、ユーザーは1つの投稿に対して1つしかいいねできない。このため、いいねの削除は、ユーザーIDと投稿IDのみで、どのいいねを削除するか特定できるため、:idを必要としない。それに対し、↑のcommentsはユーザーは1つの投稿に対し、複数コメントできるため、削除をするには、[:id]で特定する必要があるのでresourcesとなる。
      resource :likes, only: [:create, :destroy]
    end

    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :comments, only: [] do
      resources :reports, only: [:new, :create]
    end

    resources :reports, only: [:destroy] do
      # idがいらないネストの書き方
      collection do
        get :complete
      end
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 管理者用認証系 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  # namespaceメソッド: ブロック内に書かれたルーティングはすべて `/admin/〜` というパスになり、引数のモジュール（シンボル）をコントローラの中から探し出して、ルーティングするようになる。「scope module: シンボル」と比べるとpathやprefixが変更される。
  namespace :admin do
    root to: "homes#top"
    delete "/user/:id", to: "homes#destroy_user", as: "destroy_user"
    get "/style_cheatsheet", to: "homes#style_cheatsheet"

    post "/languages", to: "post_options#create_language_option", as: "create_language_option"
    delete "/language/:id", to: "post_options#destroy_language_option", as: "destroy_language_option"
    resources :post_options, only: [:index]

    resources :users, only: [:show]

    resources :interviews, only: [:new, :create] do
      collection do
        get :edit_all
        patch :update_all
      end
    end

    resources :reports, only: [:index, :update] do
      member do
        get :feedback
      end
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController
  # style_cheatsheet アクションは認証スキップ
  skip_before_action :authenticate_admin!, only: [:style_cheatsheet]

  def top
    @q = User.where.not(email: User::GUEST_USER_EMAIL).ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def style_cheatsheet
    @sections = [
      { id: 'margin', title: 'マージン' },
      { id: 'padding', title: 'パディング' },
      { id: 'title', title: 'タイトル' },
      { id: 'color', title: '文字色' },
      { id: 'backgroundcolor', title: '背景色' },
      { id: 'fontsize', title: 'フォントサイズ' },
      { id: 'border', title: 'ボーダー' },
      { id: 'button', title: 'ボタン' },
      { id: 'link', title: 'リンク' },
      { id: 'section', title: 'セクション' },
      { id: 'inner', title: 'インナー' },
      { id: 'col2', title: '2カラムレイアウト' },
      { id: 'menu', title: 'メニュー' },
      { id: 'scrollposition', title: 'スクロール位置調整' },
      { id: 'code', title: 'コードブロック' },
      { id: 'startset', title: 'ページスタートセット' },
      { id: 'field', title: 'フォームフィールド' },
      { id: 'textalign', title: 'テキスト配置' },
      { id: 'maxh', title: '最大高さオーバーフロー' },
      { id: 'inactive', title: '非活性' },
      { id: 'profile', title: 'プロフィール' },
      { id: 'table', title: 'テーブル' },
      { id: 'diff', title: '差分' },
    ]
  end

  def destroy_user
    user = User.find(params[:id]);
    user.destroy
    redirect_to admin_root_path, notice: "ユーザー：#{user.name}を削除しました"
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<% content_for :title, "管理画面｜ユーザー一覧(ホーム)" %>
<% content_for :head do %>
  <%= stylesheet_link_tag 'admin/homes', media: 'all' %>
<% end %>
<% content_for :foot do %>
<% end %>

<div class="p-home">
  <section class="u-sec">
    <div class="u-inner-1">
        <h1 class="u-title">ユーザー一覧</h1>
        
        <%= render 'shared/search_user', url: admin_root_path, placeholder: "ユーザー名を入力してください。" %>

        <div class="u-table-1 u-ta-c">
          <table>
            <thead>
              <tr>
                <th>ユーザー名</th>
                <th>ID</th>
                <th width="15%">削除する</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <figure class="u-pf-wrap">
                      <%= link_to admin_user_path(user.id) do %>
                        <%= image_tag user.get_profile_image,
                          loading: "lazy",
                          height: 30,
                          width: 30,
                          alt: "ユーザープロフィール画像",
                          class: "" %>
                        <figcaption class="u-pf-name">
                          <%= user.name %>
                        </figcaption>
                      <% end %>
                    </figure>
                  </td>
                  <td>
                    <%= user.id %>
                  </td>
                  <td>
                    <div class="u-btn-wrap">
                      <%= link_to admin_destroy_user_path(user), method: :delete, class: 'u-btn-1 opt-size-s', data: { confirm: "本当に削除しますか？" } do %>
                        <i class="fa-solid fa-trash"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="u-paginate">
          <%= paginate @users %>
        </div>
    </div>
  </section>
</div>