config/routes.rb
Rails.application.routes.draw do
  # ユーザー用認証系: URL /users/sign_in ...
  # devise_for :users => ユーザーの ログイン、ログアウト、新規登録、パスワード変更など のルーティングやコントローラを自動的に用意する。
  # skip:オプション => 不要なルーティングを削除
  # controllers:オプション => 自分で用意したコントローラに差し替える。
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations", # サインアップやアカウント編集系
    sessions: 'public/sessions' # ログイン・ログアウト系
  }

  # ユーザー側
  # scopeメソッド: ブロック内に書かれたルーティングはpathやprefixが変更することなく、module:オプションに与えられたモジュールをコントローラの中から探し出して、ルーティングするようになる。
  scope module: :public do
    root to: "homes#top"
    get "/about", to: "homes#about"

    # as:によってprefixができる
    get "/users/:id/posts", to: "users#posts", as: "user_posts"
    get "/users/:id/groups", to: "users#groups", as: "user_groups"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]

      # idが含まれるネストの書き方
      member do
        get :relationships
      end

      resources :interviews, only: [:new, :create] do
        collection do
          get :gacha
          get :draw_gacha
          get :edit_all
          patch :update_all
        end
      end
    end

    resources :posts do
      resources :comments, only: [:create, :destroy]
      # ↓なぜresource？: resourceは「:id」を使わないURLを作る。いいね機能は、ユーザーは1つの投稿に対して1つしかいいねできない。このため、いいねの削除は、ユーザーIDと投稿IDのみで、どのいいねを削除するか特定できるため、:idを必要としない。それに対し、↑のcommentsはユーザーは1つの投稿に対し、複数コメントできるため、削除をするには、[:id]で特定する必要があるのでresourcesとなる。
      resource :likes, only: [:create, :destroy]
    end

    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :comments, only: [] do
      resources :reports, only: [:new, :create]
    end

    resources :reports, only: [:destroy] do
      # idがいらないネストの書き方
      collection do
        get :complete
      end
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 管理者用認証系 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  # namespaceメソッド: ブロック内に書かれたルーティングはすべて `/admin/〜` というパスになり、引数のモジュール（シンボル）をコントローラの中から探し出して、ルーティングするようになる。「scope module: シンボル」と比べるとpathやprefixが変更される。
  namespace :admin do
    root to: "homes#top"
    delete "/user/:id", to: "homes#destroy_user", as: "destroy_user"
    get "/style_cheatsheet", to: "homes#style_cheatsheet"

    post "/languages", to: "post_options#create_language_option", as: "create_language_option"
    delete "/language/:id", to: "post_options#destroy_language_option", as: "destroy_language_option"
    resources :post_options, only: [:index]

    resources :users, only: [:show]

    resources :interviews, only: [:new, :create] do
      collection do
        get :edit_all
        patch :update_all
      end
    end

    resources :reports, only: [:index, :update] do
      member do
        get :feedback
      end
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :reason, presence: true, on: :public
  validates :admin_feedback, presence: true, on: :admin
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  def index
    base = Report.includes(:comment, :user).order(created_at: :desc)
    
    if params[:resolved] == "true"
      @reports = base.where(resolved: true).page(params[:page]).per(10)
    elsif params[:resolved] == "false"
      @reports = base.where(resolved: false).page(params[:page]).per(10)
    else
      @reports = base.page(params[:page]).per(10)
    end
  end
  
  def update
    @report = Report.find(params[:id])
    comment = @report.comment

    hide = params[:hide_comment] == "true"

    if hide
      comment.update(is_active: false)
    else
      comment.update(is_active: true)
    end

    # report_params.merge(resolved: true) => resolvedの変更はフォームにはないため、ストパラ「report_params」だけでは変更されない。merge(resolved: true)によって、ハッシュをストパラと合成させる。
    @report.assign_attributes(report_params.merge(resolved: true))
    if @report.valid?(:admin)
      @report.save(validate: false)
      redirect_to admin_reports_path, notice: '通報への対応が完了しました'
    else
      flash.now[:alert] = '通報処理に失敗しました'
      render :feedback
    end
  end
  
  def feedback
    @report = Report.find(params[:id])
  end
  
  private

  def report_params
    params.require(:report).permit(:admin_feedback)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/feedback.html.erb
<% content_for :title, "通報｜フィードバック" %>
<% content_for :head do %>
<% end %>
<% content_for :foot do %>
<% end %>
<% content_for :body_class, "" %>

<section class="u-sec">
  <h1 class="u-title">通報に対するフィードバック</h1>
  <div class="u-inner-1">
    <div class="u-vert-50">
      <article>
        <h2 class="u-title-2">対象のコメント</h2>
        <p><%= @report.comment.content %></p>
        <p class="u-ta-r u-mt-10">by <%= @report.comment.user.name %></p>
      </article>

      <article>
        <h2 class="u-title-2">通報理由</h2>
        <p><%= @report.reason %></p>
        <p class="u-ta-r u-mt-10">by <%= @report.user.name %></p>
      </article>

      <%= form_with model:@report, url: admin_report_path(@report), method: :patch, local: true, class: "u-vert-50" do |f| %>
        <div>
          <h2 class="u-title-2 u-mb-50">コメントを非表示にしますか？</h2>
          <div class="u-flex-center u-gap-30" id="js-raidowrap-feedback">
            <label>
              <%= radio_button_tag :hide_comment, "true", params[:hide_comment] == "true", checked: true %> 非表示にする
            </label>
            <label>
              <%= radio_button_tag :hide_comment, "false", params[:hide_comment] == "false" %> 非表示にしない
            </label>
          </div>
        </div>

        <div>
          <h2 class="u-title-2">フィードバック</h2>
          <%= render 'public/shared/field_error', object: @report, field: :admin_feedback %>
          <%= f.text_area :admin_feedback, class: "u-field-text_area", placeholder: "通報者に対してのメッセージを記入してください。", id: "js-admin_feedback", value: "コメントを非表示にいたします。" %>
        </div>

        <div class="u-btn-wrap">
          <%= f.submit "フィードバックを送信", class: "u-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/reports/index.html.erb
<% content_for :title, "通報｜一覧" %>
<% content_for :head do %>
<% end %>
<% content_for :foot do %>
<% end %>
<% content_for :body_class, "" %>

<section class="u-sec">
  <div class="u-inner-3">
    <h1 class="u-title">通報一覧</h1>

    <div class="u-btn-wrap opt-even">
      <%= link_to "未対応のみ", admin_reports_path(resolved: "false"), class: "u-btn" %>
      <%= link_to "対応済みのみ", admin_reports_path(resolved: "true"), class: "u-btn" %>
      <%= link_to "すべて表示", admin_reports_path, class: "u-btn" %>
    </div>

    <div class="u-table-1 u-mt-50">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>コメント</th>
            <th>通報者</th>
            <th>理由</th>
            <th>状態</th>
            <th>対応</th>
          </tr>
        </thead>
        <tbody class="u-ta-c">
          <% @reports.each do |report| %>
            <tr>
              <td>
                <%= report.id %>
              </td>
              <td>
                <%= truncate(report.comment.content, length: 10) %>
              </td>
              <td>
                <%= report.user.name %>
              </td>
              <td>
                <%= truncate(report.reason, length: 10) %>
              </td>
              <td>
                <%= report.resolved? ? "対応済み" : "未対応" %>
              </td>
              <td>
                <div class="u-btn-wrap">
                  <%= link_to "対応する", feedback_admin_report_path(report.id), class: 'u-btn opt-size-ss' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="u-paginate">
      <%= paginate @reports %>
    </div>
  </div>
</section>